version: "3.9"

# Define the services that make up the application
services:
  # PostgreSQL service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - app-db:/var/lib/postgresql/data

  # Main app service
  app:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "3005:3005"
    deploy:
      mode: replicated
      replicas: 3 # Set the number of replicas for the service
      resources: # Set the resource limits and reservations for the service
        limits:
          cpus: "0.50" # Set the CPU limit for the service
          memory: 50M # Set the memory limit for the service
        reservations:
          cpus: "0.25" # Set the CPU reservation for the service
          memory: 20M # Set the memory reservation for the service
      restart_policy:
        condition: on-failure # Set the restart condition for the service
        delay: 5s # Set the delay before restarting the service
        max_attempts: 3
        window: 120s
volumes:
  app-db:
